version: '3.1'

services:
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
  # volumes:
  #   - /Users/andrey/docker/mongodb:/mongo/db
  # Use root/example as user/password credentials

  yes-admin-ui:
    build: ../yes-admin-ui
    # image: nickmorton/yes-admin-ui
    ports:
      - 80:80

  yes-admin-api:
    build: ../yes-admin-api
    # image: nickmorton/yes-admin-api:1.0.0
    expose:
      - 3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/yes-admin
